#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/lib";
use Image::Magick;
use Data::Dumper;
use CoastLib;
use LIDAR::ASCII;
use strict;
use warnings;
use Getopt::Long;

my $scale;
GetOptions (
                  "scale"  => \$scale)   # flag
or die("Error in command line arguments\n");

my $BASEDIR = "$FindBin::Bin/..";
my $input = $ARGV[0];
my $output = $ARGV[1];
my $NODATA_color = 'red';
my $min = 0;
my $max = 255;

my $lidar = LIDAR::ASCII->read( $input );
if( !defined $lidar->{NODATA_value} ) { die "undefined NODATA_value: $input"; }

if( $scale )
{
	$max = -1000;
	$min = 10000;
	for my $y ( 0..($lidar->{nrows}-1) )
	{
		my $row = $lidar->{cells}->[$y];
		CELL: for my $x ( 0..($lidar->{ncols}-1) )
		{
			my $cell = $row->[$x];
			if( !defined $cell ) { die "undefined cell: $input $x,$y"; }
			if( $cell eq "" ) { die "undefined cell: $input $x,$y"; }
			next CELL if( $cell == $lidar->{NODATA_value} );
			if( $cell > $max ) { $max = $cell; }
			if( $cell < $min ) { $min = $cell; }
		}
	}
}

my $image = Image::Magick->new;
$image->Set(size=>$lidar->{'ncols'}.'x'.$lidar->{'nrows'});
$image->ReadImage('canvas:white');

for my $y ( 0..($lidar->{nrows}-1) )
{
	my $row = $lidar->{cells}->[$y];
	for my $x ( 0..($lidar->{ncols}-1) )
	{
		my $cell = $row->[$x];
		my $color;
		if( !defined $cell ) { die "undefined cell: $input $x,$y"; }
		if( $cell eq "" ) { die "undefined cell: $input $x,$y"; }
		if( $cell == $lidar->{NODATA_value} )
		{
			$color = $NODATA_color;
		}
		else
		{
			my $ratio = ($cell-$min)/($max-$min);
			$ratio=0 if( $ratio < 0 );
			$ratio=1 if( $ratio > 1 );
			my $intensity = 255*255*$ratio;
			$color = "$intensity,$intensity,$intensity,0";
		}
		$image->Set("pixel[$x,$y]"=>$color);
	}
}
$image->write( "png:$output" );


