#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/lib";
use Image::Magick;
use Data::Dumper;
use CoastLib;
use strict;
use warnings;

# params: infile infile infile... outfile

my $BASEDIR = "$FindBin::Bin/..";
my $output = pop @ARGV;
my @inputs = @ARGV;

my @lidars = ();
my $xllcorner;
my $yllcorner;
my $xurcorner; #urcorner is the cell up and to the right of the top right cell
my $yurcorner; 
my $cellsize;
my $NODATA_value;
INPUT: foreach my $input ( @inputs )
{
	my $lidar = CoastLib::readLidarAsc( $input );
	push @lidars, $lidar;
	my $a_xllcorner = $lidar->{xllcorner};
	my $a_yllcorner = $lidar->{yllcorner};
	my $a_xurcorner = $lidar->{xllcorner} + $lidar->{ncols}*$lidar->{cellsize};
	my $a_yurcorner = $lidar->{yllcorner} + $lidar->{nrows}*$lidar->{cellsize};
	if( !defined $xllcorner )
	{
		$xllcorner = $a_xllcorner;
		$yllcorner = $a_yllcorner;
		$xurcorner = $a_xurcorner;
		$yurcorner = $a_yurcorner;
		$cellsize = $lidar->{cellsize};
		$NODATA_value = $lidar->{NODATA_value};
		next INPUT;
	}
	if( $cellsize != $lidar->{cellsize} ) 
	{
		die "Cellsize mismatch";
	}
	if( $a_xllcorner < $xllcorner ) { $xllcorner = $a_xllcorner; }
	if( $a_yllcorner < $yllcorner ) { $yllcorner = $a_yllcorner; }
	if( $a_xurcorner > $xurcorner ) { $xurcorner = $a_xurcorner; }
	if( $a_yurcorner > $yurcorner ) { $yurcorner = $a_yurcorner; }
}
my $nrows = ($yurcorner-$yllcorner)/$cellsize;
my $ncols = ($xurcorner-$xllcorner)/$cellsize;

my $out_lidar = CoastLib::LidarAsc->new( 
	cellsize => $cellsize,
	NODATA_value => $NODATA_value,
	xllcorner => $xllcorner,
	yllcorner => $yllcorner,
	nrows => $nrows,
	ncols => $ncols
);

foreach my $lidar ( @lidars )
{
	$out_lidar->add( $lidar );
}
$out_lidar->write( $output );
exit;
