#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/../lib";
use CoastLib;
use LIDAR::ASCII;
use Data::Dumper;

my $BASEDIR = "$FindBin::Bin/../..";
my $source = "$BASEDIR/Data";

use strict;
use warnings;

my @files = CoastLib::find_all( $source );
my $map = {};
foreach my $file ( sort @files )
{
	if( $file =~ m/^(.*\.asc)\.\d+$/ )
	{
		push @{$map->{$1}},$file;	
	}
}

foreach my $outfilename ( keys %$map )
{
	my $lidar;
	INFILE: foreach my $infilename ( @{$map->{$outfilename}} )
	{
		# We'll only deal with cellsize = 1 
		print "Reading: $infilename\n";
		my $nextlidar = LIDAR::ASCII->read( "$source/$infilename" );
		next INFILE if( $nextlidar->{cellsize} != 1 );
		if( defined $lidar )
		{
			$lidar->add( $nextlidar );
		}	
		else
		{
			$lidar = $nextlidar;
		}
	}
die if !defined $lidar;
	$lidar->write( "$source/$outfilename" );
}
