#!/usr/bin/perl

# assumes GDAL & ECW libraries are installed and on the path

use FindBin;
use lib "$FindBin::Bin/../lib";
use CoastLib;
my $BASEDIR = "$FindBin::Bin/../..";
my $source = "$BASEDIR/Data/Aerial/2013/ECW";
my $target = "$BASEDIR/Data/Aerial/2013/JPEG";

use strict;
use warnings;

mkdir $target unless -d $target;

my @files = CoastLib::find_all( $source );
my $sets = {};
`unlink /tmp/src.ecw`;
FILE: foreach my $file ( @files )
{
	# try to work out the bits of this filename into something logical
	print $file."\n";
	$file =~ m/^\/(\d\d_\d\d)\.ecw(.*?)$/;
	my $outfile = "$1.jpg$2";
	`ln -s $source/$file /tmp/src.ecw`;
	my $cmd = "gdal_translate -of jpeg /tmp/src.ecw $target/$outfile";
	print "$cmd\n";
	`$cmd`;
	`unlink /tmp/src.ecw`;
}



exit;
